import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

import { site } from "@/lib/site";
import { Backdrop } from "@/components/effects/Backdrop";
import { Nav } from "@/components/navigation/Nav";
import { Footer } from "@/components/layout/Footer";
import { CommandPaletteProvider } from "@/components/navigation/CommandPaletteProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: site.title,
    template: `%s — ${site.alias}`,
  },
  description: site.description,
  applicationName: site.alias,
  authors: [{ name: site.name, url: site.github }],
  creator: site.name,
  keywords: [
    "Meeth Waghela",
    "Ghostyy",
    "AI engineer",
    "cybersecurity",
    "anomaly detection",
    "full stack developer",
    "Next.js",
    "Python",
    "portfolio",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: site.url,
    siteName: site.alias,
    title: site.title,
    description: site.description,
    locale: "en_US",
    // The image itself is generated by app/opengraph-image.tsx and renamed to
    // og.png by scripts/finalize-export.mjs, so that GitHub Pages serves it
    // with an image Content-Type. Declared explicitly here to point at the
    // renamed path rather than Next's extensionless default.
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: `${site.alias} — ${site.name} — ${site.tagline}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: site.title,
    description: site.description,
    images: ["/og.png"],
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

export const viewport: Viewport = {
  themeColor: "#050509",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable} ${jetbrainsMono.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-screen antialiased">
        <Backdrop />
        <CommandPaletteProvider>
          <Nav />
          <main id="main" className="pt-16">
            {children}
          </main>
          <Footer />
        </CommandPaletteProvider>
      </body>
    </html>
  );
}
